# Introduction to Deep Learning with TensorFlow

---


## Case:
Kita akan membuat model deep learning untuk mengetahui hubungan dua buah angka. Sebagai contoh kita mempunya data dalam variabel xs dan ys sebagai berikut:

xs = (-1.0,  0.0, 1.0, 2.0, 3.0, 4.0)

ys = (-3.0, -1.0, 1.0, 3.0, 5.0, 7.0)

Dengan menggunakan model matematika eleminasi/subtitusi maka diperoleh fungsi matematika sebagai berikut:

**y = 2x -1**

Jadi bagaimana kita melatih Neural Network untuk melakukan tugas yang sama? Dengan menggunakan data!



## Import Library

Mari kita mulai dengan import library **TensorFlow** dan menyebutnya **tf**.

import library **numpy** dan menyebutnya **np** yang membantu merepresentasikan data sebagai array dengan mudah dan untuk mengoptimalkan operasi numerik.

import **keras** yang digunakan sebagai kerangka kerja untuk membangun Neural Network.

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

print("the version of tensorflow that use in this session is " + tf.__version__)

the version of tensorflow that use in this session is 2.9.2


## Create simple Neural Network

Kita akan membangun model neural network menggunakan kelas **Keras Sequential** yang memungkinkan untuk mendefinisikan jaringan sebagai urutan lapisan.

In [ ]:
# Build a simple Sequential model
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

Langkah selanjutnya adalah kita menentukan parameter **'loss'** dan **'optimizer'**

**Loss function** mengukur jawaban yang ditebak terhadap jawaban benar yang diketahui dan mengukur seberapa baik atau seberapa buruknya.

**Optimizer function** untuk membuat tebakan lain. Berdasarkan bagaimana fungsi kerugian berjalan, ia akan mencoba meminimalkan kerugian.

In [ ]:
# Compile the model
model.compile(optimizer='sgd', loss='mean_squared_error')

## The Data

In [ ]:
# Declare model inputs and outputs for training
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

## Train The Model

In [ ]:
# Train the model
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 378ms/step - loss: 18.9808
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 15.1944
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 12.2100
Epoch 4/500
1/1 [==============================] - 0s 7ms/step - loss: 9.8568
Epoch 5/500
1/1 [==============================] - 0s 6ms/step - loss: 8.0003
Epoch 6/500
1/1 [==============================] - 0s 6ms/step - loss: 6.5346
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 5.3766
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 4.4606
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 3.7353
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 3.1599
Epoch 11/500
1/1 [==============================] - 0s 10ms/step - loss: 2.7028
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 2.3386
Epoch 13/500
1/1 [==============================] - 0s 

## Let's Predict with new input data

In [ ]:
# Make a prediction with several data
new_xs = [10.0,13.0,16.0,19.0,23.0]

for i in new_xs:
  print(model.predict([i]))

1/1 [==============================] - 0s 65ms/step
[[18.98085]]
1/1 [==============================] - 0s 21ms/step
[[24.972523]]
1/1 [==============================] - 0s 28ms/step
[[30.964197]]
1/1 [==============================] - 0s 24ms/step
[[36.95587]]
1/1 [==============================] - 0s 21ms/step
[[44.94477]]


# New Case: Classification with Iris Dataset with TensorFlow

Pada case ini, kita akan mengklasifikasikan spesies bunga

### Import Library

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

### Load Dataset

In [ ]:
# Read CSV
ds = pd.read_csv("/content/Iris_dataset.csv")
ds.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Split the data into x and y

In [ ]:
# Split into x and y
x = ds.iloc[:,1:5].values
y = ds.iloc[:,5].values

In [ ]:
# print the first five
print(x[0:5])
print(y[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [ ]:
#print the shape
print(x.shape)
print(y.shape)

(150, 4)
(150,)


### Convert Target with LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Convert Target into One Hot Encoding

In [ ]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


### Split the data into Train Test

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, Y, test_size=0.2, random_state=12)

In [ ]:
print(X_train[0:5])

[[5.1 3.5 1.4 0.3]
 [5.5 2.4 3.7 1. ]
 [6.3 2.9 5.6 1.8]
 [5.5 4.2 1.4 0.2]
 [5.8 2.7 5.1 1.9]]


In [ ]:
print(y_train[0:5])

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]]


In [ ]:
print(X_test[0:5])

[[5.  3.5 1.3 0.3]
 [6.3 2.5 5.  1.9]
 [4.4 3.  1.3 0.2]
 [5.7 2.8 4.1 1.3]
 [6.8 3.2 5.9 2.3]]


In [ ]:
print(y_test[0:5])

[[1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


### Define The Model

In [ ]:
#Define a model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

#Compile the model
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
# Train The Model
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 0s 5ms/step - loss: 1.1496 - accuracy: 0.4833
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 0.9944 - accuracy: 0.6333
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 0.9138 - accuracy: 0.6417
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8656 - accuracy: 0.6250
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8336 - accuracy: 0.6000
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8153 - accuracy: 0.6500
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7939 - accuracy: 0.6083
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7841 - accuracy: 0.6083
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 0.7720 - accuracy: 0.6667
Epoch 10/100
3/3 [==============================] - 0s 5ms/step - loss: 0.7599 - accuracy: 0.6500
Epoch 11/100
3/3 [===========

#### Evaluate the model with test data

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.3113909363746643
Test accuracy: 0.9333333373069763


### Predict test data

In [ ]:
# predict
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 38ms/step


array([[0.9682737 , 0.03000153, 0.00172472],
       [0.00350161, 0.23083979, 0.7656586 ],
       [0.9419522 , 0.05409488, 0.00395283],
       [0.03024708, 0.5754176 , 0.3943354 ],
       [0.00146884, 0.1762885 , 0.8222427 ],
       [0.00478713, 0.3382404 , 0.6569724 ],
       [0.00290488, 0.20595354, 0.7911416 ],
       [0.96119046, 0.03685803, 0.00195157],
       [0.00099453, 0.16674775, 0.8322576 ],
       [0.9109167 , 0.08098239, 0.00810089],
       [0.01928312, 0.49827623, 0.48244065],
       [0.97716933, 0.02179259, 0.00103806],
       [0.9544326 , 0.04238553, 0.00318189],
       [0.96553105, 0.03244326, 0.00202564],
       [0.02311562, 0.6253129 , 0.35157144],
       [0.00382181, 0.37625122, 0.619927  ],
       [0.00209947, 0.24326138, 0.7546392 ],
       [0.02467863, 0.52626085, 0.44906053],
       [0.9558003 , 0.04146275, 0.00273698],
       [0.00844204, 0.40368408, 0.5878738 ],
       [0.9420268 , 0.05414997, 0.00382324],
       [0.03601278, 0.58769965, 0.3762875 ],
       [0.

In [ ]:
# print actual and predicted value
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [0 2 0 1 2 2 2 0 2 0 1 0 0 0 1 2 2 1 0 1 0 1 2 1 0 2 1 1 0 0]
Predicted: [0 2 0 1 2 2 2 0 2 0 1 0 0 0 1 2 2 1 0 2 0 1 2 1 0 2 2 1 0 0]


# Lets try by your self

Imagine, you are a Data Scientist at property company, and your boss need your help to predict the price of house with the data such as:

num_of_bedroom = (1,2,3,4,5,6,7)
price_of_house = (10000,20000,30000,40000,50000,60000,70000)


Proble what if the number of bedroom is **13**
Use the Neural Network to Solve This!

## Import the Library

## Create The Model

### Choise the optimizer function and loss function

## Create the variable that contain the data

## Train The Model

## Lets Predict